[tool.poetry]
name = "beet"
version = "0.1.3"
description = "The Minecraft pack development kit"
authors = ["Valentin Berlier <berlier.v@gmail.com>"]
license = "MIT"

homepage = "https://github.com/vberlier/beet"
repository = "https://github.com/vberlier/beet"
documentation = "https://github.com/vberlier/beet"

readme = "README.md"

keywords = [
  "beet",
  "minecraft",
  "datapack",
  "resourcepack",
  "mcfunction"
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
nbtlib = "^1.8.1"
pathspec = "^0.8.1"
Pillow = "^8.0.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.1.2"
rope = "^0.18.0"
pytest-minecraft = "^0.1.1"
isort = "^5.6.4"

[tool.black]
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | node_modules
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
