name: Docs

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "pyproject.toml"

jobs:
  main:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-in-project: true
      - name: Setup cache
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install
      - name: Build and deploy documentation
        run: poetry run mudkip build --check --update-gh-pages
